// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('asads', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('asads', async function() {
    await driver.get("https://www.xampro.org/")
    await driver.manage().window().setRect(1224, 816)
    await driver.findElement(By.css(".splash-screen-main-wrap")).click()
    await driver.findElement(By.css(".profile-view-btn > #basic-nav-dropdown")).click()
    {
      const element = await driver.findElement(By.css(".profile-view-btn > #basic-nav-dropdown"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("li:nth-child(8) span")).click()
    await driver.close()
  })
})
